const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const backend=process.env.AUPET_BACKEND||'D:/GITHUB/aupet-new/backend';
function bridge(data,status=false){return new Promise((resolve,reject)=>{const child=spawn(path.join(backend,'.venv/Scripts/python.exe'),['-B','-X','utf8',path.join(__dirname,'ai_bridge.py'),...(status?['--status']:[])],{windowsHide:true,env:{...process.env,AUPET_BACKEND:backend}});let output='';const timer=setTimeout(()=>{child.kill();reject(Error('AI 回答超时，请重试。'));},40000);child.stdout.on('data',c=>output+=c);child.stderr.resume();child.on('error',()=>{clearTimeout(timer);reject(Error('无法启动原项目 AI 服务。'));});child.on('close',code=>{clearTimeout(timer);try{if(code!==0)throw Error();resolve(JSON.parse(output));}catch{reject(Error('原项目 AI 服务启动失败，请检查配置。'));}});child.stdin.on('error',()=>{});child.stdin.end(JSON.stringify(data));});}
let active=0;
const server=http.createServer(async(req,res)=>{const json=(s,v)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(v));};const route=new URL(req.url,'http://127.0.0.1').pathname;
if(route==='/api/tutor/status'&&req.method==='GET'){try{return json(200,await bridge({},true));}catch{return json(503,{configured:false});}}
if(route==='/api/tutor'&&req.method==='POST'){
 if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`)return json(403,{error:'请求来源不允许。'});
 if(!req.headers['content-type']?.startsWith('application/json'))return json(415,{error:'需要 JSON 请求。'});
 if(active>=2)return json(429,{error:'正在处理其他问题，请稍后重试。'});active++;
 try{let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>50000)return json(413,{error:'代码或对话过长。'});}let d;try{d=JSON.parse(raw);}catch{return json(400,{error:'请求格式不正确。'});}if(!d||typeof d.question!=='string'||!d.question.trim()||d.question.length>1500)return json(400,{error:'请输入 1～1500 字的问题。'});const history=Array.isArray(d.history)?d.history.slice(-10).filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').map(m=>({role:m.role,content:m.content.slice(0,4000)})):[];const result=await bridge({question:d.question,history,context:{course:d.course,language:d.language,task:d.task,code:d.code,input:d.input,result:d.result}});return json(result.error?502:200,result);}catch(e){return json(502,{error:e.message});}finally{active--;}}
const file=({'/':'index.html','/index.html':'index.html','/style.css':'style.css','/app.js':'app.js','/tutor.js':'tutor.js','/courses.js':'courses.js','/python-runtime.js':'python-runtime.js','/python-worker.js':'python-worker.js'})[route];if(!file||req.method!=='GET')return json(404,{error:'页面不存在。'});res.writeHead(200,{'Content-Type':file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(fs.readFileSync(path.join(__dirname,file)));});
server.listen(Number(process.env.PORT)||4173,'127.0.0.1',()=>console.log('Learning app ready'));
